### ISSUE TITLE
Bugs in runtime/python/yolo_general_inference/yolo_inference.py

### ISSUE THREAD

**Issue by rahultp-ign** [hailo-ai/Hailo-Application-Code-Examples#232]
Getting errors while running `runtime/python/yolo_general_inference/yolo_inference.py`.
```
  File "./yolo_inference.py", line 56
    'yolox': 
    ^
SyntaxError: invalid syntax
```
```
Given input data dtype (uint8) is different than inferred dtype (float32). conversion for every frame will reduce performance
Traceback (most recent call last):
  File "./yolo_inference.py", line 449, in <module>
    img = letterbox_image(batch_images[j], (width, height))
TypeError: list indices must be integers or slices, not tuple
```

**Comment by omerwer** [comment]
Hi @rahultp-ign,
Yes, you are correct, there was a missing ',' that caused this error. It's fixed now.
Thank you
