### ISSUE TITLE
Remove bytetracker dependency from requirements.txt of /runtime/python/detection_with_tracker/

### ISSUE THREAD

**Issue by sebastianfis** [hailo-ai/Hailo-Application-Code-Examples#322]
The bytetracker package includes dependencies on very old versions of torch and lap packages. That raises compatibility issues with python versions >= 3.11 (it's not impossible getting it to run, but it's not easy and certanily not straightforward). The way I see it, the code does not make use of the bytetracker package (anymore?), but instead uses the byte track implementation of supervision. I suggets to remove this dependency to make installation on newer python versions easier.

**Comment by sebastianfis** [comment]
Are you sure this is true for version 0.19.0? I just checked the pyproject.toml of this release: https://github.com/roboflow/supervision/blob/55f93a85b6a76c710c764f4f96dfb4d8cc73bb90/pyproject.toml

**Comment by sebastianfis** [comment]
For everyone who is also trying to run this on a RPi 5 and is stuck at the same point: 

1.  You have to download and install hailort v 4.18 FIRST:

```shell
pip install ~/Downloads/hailort-4.18.0-cp311-cp311-linux_aarch64.whl
``` 

2.  Then remove bytetracker from the 1st line of requirements.txt (e.g. using nano). And install requirements via pip: 

```shell
pip install -r requirements.txt 
``` 
This will result in a compatibility issue, as `hailort==4.18` requires `numpy==1.23.3`, but requirements.txt does not define a certain numpy version, so the packages that require it will install the newest one:
```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hailort 4.18.0 requires numpy==1.23.3, but you have numpy 2.1.3 which is incompatible.
``` 

3. The min. Version of `numpy `for all other pacakges except `hailort ` is `numpy==1.23.5`. Luckily the detection with tracker example also works with `numpy==1.23.5`, so you can just fix it with 
```shell
pip install numpy==1.23.5
``` 
Alternatively, you can just add a line `numpy==1.23.5` to requirements.txt in step 2 to force this version already during requirements installation. 

Afterwards the example runs smoothly on my RPi5. Note that the HEF file included in the example might not work. I recommend using either yolov8m.hef or yolov10b.hef from the Hailo model zoo and run by using:
```shell
python detection_with_tracker.py -i input_video.mp4 -o output_video.mp4 -l coco.txt -s 0.5 -n ~/Downloads/yolov10b.hef
``` 
Happy coding!

**Comment by owaisasghar** [comment]
Subject: ImportError: libhailort.so.4.18.0 Missing in Hailo Detection Example

Description:
I am encountering an issue while running the detection_with_tracker.py script from the Hailo Application Code Examples. The script fails to start due to a missing shared library (libhailort.so.4.18.0). Below are the details:


```
Traceback (most recent call last):
  File "/home/uwais/Hailo-Application-Code-Examples/runtime/python/detection_with_tracker/detection_with_tracker.py", line 16, in <module>
    from utils import HailoAsyncInference
  File "/home/uwais/Hailo-Application-Code-Examples/runtime/python/utils.py", line 8, in <module>
    from hailo_platform import (HEF, VDevice,
  File "/home/uwais/Hailo-Application-Code-Examples/runtime/python/detection_with_tracker/myenv/lib/python3

```

**Comment by hailocs** [comment]
Thee Python object detection example now includes integrated ByteTrack support with no additional dependencies required
